### ISSUE TITLE
Move 2 MSVC warnings outside if ENABLE_WARNINGS

### ISSUE THREAD

**Issue by HackingPheasant** [HackingPheasant/manga-manager#7]
https://github.com/HackingPheasant/manga-manager/blob/08cb83ab2c133d3a7353d1210d83d4a7c2dc090f/cmake/CompilerWarnings.cmake#L111-L112

Best to move these out of the ENABLE_WARNINGS section code and enable them unconditionally.

Edit: Move  `NOMINMAX` to an `if(WINDOWS)` block

**Comment by hermantrym** [comment]
I think it is necessary to define the same macros as in the if and else if branches. Even if you don’t use another compiler than Visual Studio, gcc or clang today, it would be a shame to halt the compilation on another compiler just because you didn’t define the macros for it.

**Comment by HackingPheasant** [comment]
Yeah, good point I'll be best moving the NOMINMAX into something like an `if(WINDOWS)` block, instead of it being added into each compiler (or at the moment only being applied to MSVC).
